### PR TITLE
Ensure cli has the version

### PR DESCRIPTION
**Pull request by enerestar**
Signed-off-by: Serene Lim <serene@hedera.com>

### CODE REVIEW

**Comment by calvinchengx** [comment]
There should be only one single source of truth for version.

It should either be in gradle.properties or application.properties and not in both. 

Does this implementation do that? 

Perhaps we can change the groovy code in Gradle to 

```
processResources {
     filesMatching('gradle.properties') {
         expand(project.properties)
     }
 }
```

(And of course we have to reference “version” accordingly because the key name is “version” in gradle.properties)

And that would work.

**Comment by enerestar** [comment]
we actually dont need a separate gradle.properties. But removing that would mean the release script in bash will need to change how it retrieves the version, and I have not figured out how to write that :D

**Comment by calvinchengx** [comment]
> we actually dont need a separate gradle.properties. But removing that would mean the release script in bash will need to change how it retrieves the version, and I have not figured out how to write that :D

That is exactly what is implied in the above.

Either change groovy to use Gradle properties or change bash to read application properties.

It’s either or. We must not have two places where version is specified.

Either way is fine with me. But this issue is only closed if we have a single source of truth for version.

**Comment by calvinchengx** [comment]
Also, implement the “version” command as requested by @Cooper-Kunz in this PR.

**Pull request merged**
